### PR TITLE
Add node configuration property to set msg.topic (#23)

### PR DESCRIPTION
**Pull request by dimw**
- Add node configuration property to set `msg.topic`
- Update docs

### CODE REVIEW

**Comment by StephanStS** [comment]
Also the README.md needs to be extended with the new feature when merging the PR.

**Comment by StephanStS** [comment]
@c5te1n: Could you please update the node on npmjs.com.  
Then I can update it on my NR instance and try to generate some README.md extensions if I understand the changes :-)

**Comment by c5te1n** [comment]
@StephanStS Just did with some additional changes from the latest commit. Should be available now.

**Comment by StephanStS** [comment]
@c5te1n: Perfect. I added minor text changes as a proposal within PR #25.

**Pull request merged**
